# Generated by Django 4.1.3 on 2022-11-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('tamanhos', models.CharField(max_length=255)),
            ],
        ),
    ]
