# Generated by Django 4.1.3 on 2022-11-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.CharField(max_length=10),
        ),
    ]
