# Generated by Django 4.1.3 on 2022-11-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0002_alter_produtos_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
