# Generated by Django 4.1.3 on 2022-11-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0003_produtos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
