# Generated by Django 4.1.3 on 2022-11-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0005_produtos_desc_alter_produtos_tamanhos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
