# Generated by Django 4.1.3 on 2022-11-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0006_alter_produtos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
